# Generated by Django 4.1.3 on 2022-11-12 02:36

from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=images.models.history_images)),
                ('history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='history.history')),
            ],
        ),
    ]
