# Generated by Django 4.1.3 on 2022-11-10 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id_history', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('onset_of_symptoms', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('pain_local', models.CharField(blank=True, max_length=100, null=True)),
                ('pain_type', models.CharField(blank=True, max_length=100, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='schedules.schedule')),
            ],
            options={
                'db_table': 'histories',
                'managed': (True,),
            },
        ),
    ]
