# Generated by Django 4.1.3 on 2022-11-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('address_number', models.IntegerField(blank=True, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=60, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'patients',
                'managed': True,
            },
        ),
    ]
