# Generated by Django 4.1.3 on 2022-11-10 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_schedule', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canceled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('schedule_type', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='patient.patient')),
            ],
            options={
                'db_table': 'schedules',
                'managed': True,
                'unique_together': {('schedule_datetime', 'patient_id')},
            },
        ),
    ]
